In [2]:
#importing numpy module
import numpy as np

#defining a matrix using np.array() method
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

#printing the matrix
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

#adding A and B matrices
C = A + B
print(C)

[[ 6  8]
 [10 12]]


In [6]:
import numpy as np
A = np.array([[1 , 2],[3 , 4]])
B = np.array([[0 , 1],[2 , 1]])

# Matrix Substraction
C = A - B
print(C)

[[1 1]
 [1 3]]


In [8]:
import numpy as np
A = np.array([[4 , 2],[6 , 8]])
B = np.array([[2 , 2],[3 , 4]])

#Matrix Division
C = A//B
print(C)

[[2 1]
 [2 2]]


In [10]:
#Matrix - Matrix Multiplication ( Dot product )
import numpy as np
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])
C = A.dot(B)
print(C)

[[19 22]
 [43 50]]


In [12]:
#matrix - vector multiplication
import numpy as np
A = np.array([[1, 2],[1 , 1]])
V = np.array([[1] , [1]])

#matrix - vector multiplication
C = A.dot(V)
print(C)

[[3]
 [2]]


In [14]:
#Matrix - Scalar multiplication
import numpy as np
A = np.array([[1,2],[3,4]])
b = 2
print(A * b)

[[2 4]
 [6 8]]
